version: "3.8"

services:
  gateway:
    environment:
      - NGINX_PORT=80
    build: .
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      audit:
        condition: service_started

  audit:
    image: ghcr.io/projekt-datascience/backend-audit:release
    env_file:
      - env

  user-management:
    image: ghcr.io/projekt-datascience/backend-user-management:release
    env_file:
      - env
