# This workflow runs tests that are defined in the "tests" directory

name: Runs tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - release

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start containers
        run: docker-compose up -d --build

      - name: Installing dependencies
        run: pip install -r requirements.txt

      - name: Running tests
        run: pytest tests

      - name: Stop containers
        if: always()
        run: docker-compose down
